feat: implement AllFlagsState
launchdarkly/cpp-sdks pull request #201
Opened 2023-08-18 22:55 UTC by cwaldren-ld

2023-08-21 18:22 UTC, cwaldren-ld commented on libs/internal/include/launchdarkly/data_model/flag.hpp
> +    using FlagVersion = std::uint64_t;
Can't fall this `Version` because it conflicts with the `Version()` method. Hmm.

2023-08-21 23:16 UTC, kinyoklion requested changes

2023-08-21 23:16 UTC, kinyoklion commented on libs/server-sdk/src/client_impl.cpp
> +    if (!Initialized()) {
This flow doesn't look right taking persistence into account. 

If the flags are in persistence, then we would evaluate all flags and provide a warning that it was called before evaluation. 

If persistence wasn't populated, and we were not initialized, then I would expect this. The variation internal method has it.

Node equivalent
```
    if (!this.initialized()) {
      const storeInitialized = await this.featureStore.initialized();
      if (storeInitialized) {
        this.logger?.warn(
          'Called allFlagsState before client initialization; using last known' +
            ' values from data store',
        );
      } else {
        this.logger?.warn(
          'Called allFlagsState before client initialization. Data store not available; ' +
            'returning empty state',
        );
        valid = false;
      }
    }
```

2023-08-21 23:16 UTC, kinyoklion commented on libs/server-sdk/src/client_impl.cpp
> +    if (!Initialized()) {
Variation internal has something similar.

2023-08-23 20:09 UTC, kinyoklion approved these changes

2023-08-23 21:10 UTC, merged